#pragma once

#include "NativeGameplayTags.h"

namespace InputTags
{
	BIGMOXIGAMES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	BIGMOXIGAMES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	BIGMOXIGAMES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	BIGMOXIGAMES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LMB);

}